# Generated by Django 3.2.3 on 2021-05-28 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 5, 28, 11, 36, 29, 487433, tzinfo=utc), verbose_name='date created')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.list')),
            ],
        ),
    ]
